In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
arr_sum=np.sum(a)
arr_avg=np.mean(a)
arr_multiply=3*a
arr_slice=a[2:7]
arr_sum_slice=np.sum(arr_slice)
arr_avg_mean=np.mean(arr_slice)
print(a)
print(arr_sum)
print(arr_avg)
print(arr_multiply)
print(arr_slice)
print(arr_sum_slice)
print(arr_avg_mean)




[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
[ 3  6  9 12 15 18 21 24 27 30]
[3 4 5 6 7]
25
5.0


In [2]:
import numpy as np
arr=np.array([[3,4,5],[6,7,8],[9,1,2]])
print(arr[1,2])
print(arr[1,])
print(arr[:,1])
print(arr.transpose())



8
[6 7 8]
[4 7 1]
[[3 6 9]
 [4 7 1]
 [5 8 2]]


In [3]:
import numpy as np
arr1=np.array([5,1,4,2])
arr2=np.array([6,10,11,7])
arr3=np.concatenate((arr1,arr2),axis=0) 
sorted=np.sort(arr3.flatten())
array1,array2=np.split(sorted,2,axis=-1)
print(arr3)
print(sorted)
print(array1)
print(array2)



[ 5  1  4  2  6 10 11  7]
[ 1  2  4  5  6  7 10 11]
[1 2 4 5]
[ 6  7 10 11]


In [4]:
import numpy as np
array=np.arange(0,4* np.pi+ np.pi/2,np.pi/2)
print(array)
sin_values=np.sin(array)
print(sin_values)
cos_values=np.cos(array)
print(cos_values)
log_values=np.log(array)
print(log_values)
exp_values=np.exp(array)
print(exp_values)
mean_sin=np.mean(sin_values)
print(mean_sin)
mean_cos=np.mean(cos_values)
print(mean_cos)
mean_log=np.mean(log_values)
print(mean_log)
mean_exp=np.mean(exp_values)
print(mean_exp)
med_sin=np.median(sin_values)
print(med_sin)
med_cos=np.median(cos_values)
print(med_cos)
med_log=np.median(log_values)
print(med_log)
med_exp=np.median(exp_values)
print(med_exp)
std_sin=np.std(sin_values)
print(std_sin)
std_cos=np.std(cos_values)
print(mean_cos)
std_log=np.std(log_values)
print(mean_log)
std_exp=np.std(exp_values)
print(std_exp)


[ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16  1.0000000e+00  3.6739404e-16 -1.0000000e+00
 -4.8985872e-16]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00  3.0616170e-16 -1.0000000e+00 -4.2862638e-16
  1.0000000e+00]
[      -inf 0.45158271 1.14472989 1.55019499 1.83787707 2.06102062
 2.24334217 2.39749285 2.53102425]
[1.00000000e+00 4.81047738e+00 2.31406926e+01 1.11317778e+02
 5.35491656e+02 2.57597050e+03 1.23916478e+04 5.96097415e+04
 2.86751313e+05]
-2.975712385932333e-17
0.11111111111111106
-inf
40222.7148375631
0.0
6.123233995736766e-17
1.8378770664093453
535.4916555247646
0.6666666666666666
0.11111111111111106
-inf
89056.36419225672


/var/folders/1l/ksmwxq4x3_19hzyb8w75g4c80000gn/T/ipykernel_26775/759102923.py:8: RuntimeWarning: divide by zero encountered in log
  log_values=np.log(array)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/_methods.py:173: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


In [5]:
import numpy as np
arr=np.arange(15,81,5)
print(arr)
arr_25=arr>25
print(arr_25)
print(arr[arr>25])



[15 20 25 30 35 40 45 50 55 60 65 70 75 80]
[False False False  True  True  True  True  True  True  True  True  True
  True  True]
[30 35 40 45 50 55 60 65 70 75 80]
