In [5]:
# Heading 1 

In [1]:
import numpy as np
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
print(z)
z[1,1]=9
output[1:4,1:4]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
import numpy as np
a=np.array([1,2,3,4,])
print(a)


a=np.ones((2,3))
print(a)




[1 2 3 4]
[[1. 1. 1.]
 [1. 1. 1.]]
